[theme]
base="light"

# Palette "bleu-gris pro"
primaryColor="#1B63A1"            # boutons & accents
backgroundColor="#EAF2FF"         # fond global (bleu très clair)
secondaryBackgroundColor="#F7FAFF" # panneaux/cartes (plus blanc)
textColor="#0B1F33"               # texte foncé lisible

font="Inter"                      # optionnel (ou "sans serif")

[server]
fileWatcherType = "none"

